services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Query\Type:
        parent: ezpublish.fieldType
        public: true
        autowire: true
        autoconfigure: false
        tags:
            - { name: ezpublish.fieldType, alias: '%ezcontentquery_identifier%' }
        arguments:
            $identifier: '%ezcontentquery_identifier%'

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Mapper\QueryFormMapper:
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: '%ezcontentquery_identifier%' }
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Form\QueryFieldFormType: ~

    EzSystems\EzPlatformQueryFieldType\eZ\Persistence\Legacy\Content\FieldValue\Converter\QueryConverter:
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: '%ezcontentquery_identifier%' }

    ezplatform.query_field_type.not_indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - { name: ezpublish.fieldType.indexable, alias: '%ezcontentquery_identifier%' }

    EzSystems\EzPlatformQueryFieldType\eZ\ContentView\FieldDefinitionIdentifierMatcher:
        calls:
            - [setRepository, ['@ezpublish.api.repository']]

    Identifier\FieldDefinition:
        alias: 'EzSystems\EzPlatformQueryFieldType\eZ\ContentView\FieldDefinitionIdentifierMatcher'
        public: true

    EzSystems\EzPlatformQueryFieldType\eZ\ContentView\QueryResultsInjector:
        arguments:
            $views: { field: '%ezcontentquery_field_view%', item: '%ezcontentquery_item_view%' }
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformQueryFieldType\eZ\Twig\QueryFieldBlockRenderer:
        decorates: ezpublish.templating.field_block_renderer.twig
        arguments:
            $innerRenderer: '@EzSystems\EzPlatformQueryFieldType\eZ\Twig\QueryFieldBlockRenderer.inner'

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\NamedQuery\Form\FieldDefinitionParametersType:
        arguments:
            $parametersSubscriber: '@EzSystems\EzPlatformQueryFieldType\eZ\FieldType\NamedQuery\Form\EventSubscriber\FieldDefinitionParametersSubscriber'
        tags:
            - { name: form.type }

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\NamedQuery\Form\EventSubscriber\FieldDefinitionParametersSubscriber:
        tags:
            - { name: kernel.event_subscriber }
