services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldRestController:
        arguments:
            $requestParser: '@ezpublish_rest.request_parser'

    EzSystems\EzPlatformQueryFieldType\API\QueryFieldService:
        arguments:
            $queryTypeRegistry: '@ezpublish.query_type.registry'

    EzSystems\EzPlatformQueryFieldType\API\QueryFieldServiceInterface: '@EzSystems\EzPlatformQueryFieldType\API\QueryFieldService'
