services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    EzSystems\EzPlatformQueryFieldType\API\ExceptionSafeQueryFieldService:
        decorates: 'EzSystems\EzPlatformQueryFieldType\API\QueryFieldServiceInterface'
